# Generated by Django 5.0.4 on 2024-04-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='price',
            new_name='filter',
        ),
    ]
