# Generated by Django 5.0.4 on 2024-04-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
