# Generated by Django 5.0.4 on 2024-04-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_price_restaurant_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='filter',
        ),
    ]
