# Generated by Django 5.0.4 on 2024-04-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_restaurant_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
