# Generated by Django 5.0.4 on 2024-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_restaurant_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='price',
            new_name='max_price',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
