# Generated by Django 5.0.4 on 2024-04-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='min_price',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
