# Generated by Django 5.0.4 on 2024-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_remove_restaurant_max_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='business_hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='end_time',
            field=models.TimeField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='start_time',
            field=models.TimeField(default=0),
        ),
    ]
