# Generated by Django 5.0.4 on 2024-04-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_remove_restaurant_business_hours_restaurant_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='start_time',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='business_hours',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
