# Generated by Django 5.0.4 on 2024-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_remove_restaurant_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_hours',
            field=models.CharField(default='', max_length=200),
        ),
    ]
