# Generated by Django 5.0.4 on 2024-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_alter_restaurant_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_hours',
            field=models.CharField(default='時', max_length=200),
        ),
    ]
